* About
Dummyparens is a simple utility providing parentheses auto-pairing and
wrapping.

When you press an opening parenthesis key it inserts the closing one
for you. If a region is selected when you press the key, the region
will be wrapped. If you wrap with { it will also indent the wrapped
region (convenient for C and the like).

This is similar to electric-pair minor mode, but with wrapping.

It's intended to be minimalistic and non-invasive as you would expect
such simple functionality to be.

For more sophisticated features, like HTML tags or LaTeX environments
handling, consider looking at [[https://github.com/Fuco1/smartparens][smartparens]].
* Configuration
** Initialization
- Create folder ~/.emacs.d if you don't have it
- Go to it and clone dummyparens there
  #+BEGIN_SRC sh
    git clone https://github.com/snosov1/dummyparens.git
  #+END_SRC
- Put this in your ~/.emacs file
  #+BEGIN_SRC elisp
    (add-to-list 'load-path "~/.emacs.d")
    (when (require 'dummyparens nil t)
      (global-dummyparens-mode))
  #+END_SRC
** Customization
You can customize dp-pairs variable to add or remove symbols that have
to be paired. E.g.
#+BEGIN_SRC elisp
  (setq dp-pairs '(
                   ("(" ")" nil)
                   ("[" "]" nil)
                   ("{" "}" dp-brace-post-handler)
                   ("\"" "\"" nil)
                   ))
#+END_SRC
